name: Continuous Integration with Github Actions

on:
  push:
    branches: 
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2.0.0
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Build Application Jar
      working-directory: ./api-spring-3
      run: mvn clean package -DskipTests

    - name: Docker Compose Build
      working-directory: ./
      run: docker compose up -d --build
      

    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/spring-boot-tres:latest ${{ secrets.DOCKER_USERNAME }}/spring-boot-tres:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot-tres:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot-tres:latest
